name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew test
      - uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: build/reports/tests/test/index.html
